# config.yaml
huggingface:
  username: "IIEleven11"  # Your Hugging Face username
  repo_name: "testv2" # Name for the repository
  
audio_processing:
  skip_transcription: false # true to skip audio transcription
  transcription_method: 1    # 1 for local Whisper, 2 for Deepgram API
  num_gpus: null            # number of GPUs to use (null for all available)
  skip_denoise_normalize: true  # true to skip denoising and normalizing
  sampling_rate: 24000

dataset:
  eval_percentage: 10   # Percentage of data for evaluation (normal ranges around 10-15%)
  speaker_name_option: "filename"  # Can be "single" or "filename". Use single if there is only one speaker. Use filename if the speaker_name is in the filename and you want to represent this in the dataset
  speaker_name: "John Doe"  # Only used if speaker_name_option is "single"
