# config.yaml
huggingface:
  username: "IIEleven11"  # Your Hugging Face username
  repo_name: "Kalypso" # Name for the repository
  
audio_processing:
  skip_transcription: false # true to skip audio transcription
  transcription_method: 1    # 1 for local Whisper, 2 for Deepgram API
  num_gpus: null            # number of GPUs to use (null for all available)
  skip_denoise_normalize: true  # true to skip denoising and normalizing
  sampling_rate: 22050
  refilter: false  # If true, this will skip transcription and all of the audio analyzing. Useful if your thresholds were too strict and you want to adjust and try again.

dataset:
  eval_percentage: 10   # Percentage of data for evaluation (normal ranges around 10-15%)
  speaker_name_option: "single"  # Can be "single" or "filename"
  speaker_name: "Kalypso"  # Only used if speaker_name_option is "single"
